import { useState } from 'react';
import { ArrowRight, BookOpenCheck, Network, Send, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { Button, PageHeader, Panel, SourceBadge } from '../components/ui';
import { investigationService } from '../services';
import type { AssistantResponse } from '../types/domain';

const prompts = ['Which entities are common across these cases?', 'What evidence supports the account connection?', 'Show the shortest path between CASE-001 and CASE-024.', 'Summarize CASE-017 using available records.'];

export function AssistantPage() {
  const [query, setQuery] = useState(''); const [asked, setAsked] = useState(''); const [answer, setAnswer] = useState<AssistantResponse>(); const [loading, setLoading] = useState(false);
  const ask = async (text = query) => { if (!text.trim()) return; setAsked(text); setLoading(true); setAnswer(await investigationService.askInvestigator(text)); setLoading(false); };
  return <><PageHeader eyebrow="Evidence-grounded assistance" title="Investigator Assistant" description="Ask questions about connected cases, entities and evidence. AI explanations are distinct from source records." />
    <div className="assistant-layout"><Panel className="assistant-main"><div className="assistant-intro"><div><Sparkles /></div><h2>Ask about the investigation graph</h2><p>Responses use the graph context and evidence references returned by the investigation service.</p><div>{prompts.map((p) => <button key={p} onClick={() => { setQuery(p); void ask(p); }}>{p}<ArrowRight /></button>)}</div></div>{asked && <div className="conversation"><div className="question"><UserRound /><div><span>Investigator</span><p>{asked}</p></div></div><div className="answer"><Sparkles /><div><span>AI-generated explanation</span>{loading ? <p className="typing">Reviewing connected records…</p> : answer && <><p>{answer.answer}</p><div className="grounding-label"><ShieldCheck size={15} />Based on {answer.recordCount} records · Requires investigator verification</div></>}</div></div></div>}<form className="assistant-input" onSubmit={(e) => { e.preventDefault(); void ask(); }}><textarea value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Ask about cases, entities, paths or supporting evidence..." rows={2}/><Button disabled={loading}><Send size={16} />Ask</Button></form></Panel><Panel title="Graph context" subtitle="Evidence returned alongside the explanation">{answer ? <div className="assistant-context"><section><h3><Network />Entities</h3><div className="id-chips">{answer.entities.map((id) => <span key={id}>{id}</span>)}</div></section><section><h3>Cases</h3><div className="id-chips">{answer.cases.map((id) => <span key={id}>{id}</span>)}</div></section><section><h3><BookOpenCheck />Evidence references</h3>{answer.evidenceIds.map((id) => <div className="mini-record" key={id}><strong>{id}</strong><SourceBadge>Synthetic NexusNet Data</SourceBadge></div>)}</section><section><h3>Suggested follow-ups</h3>{answer.suggestedQuestions.map((q) => <button className="followup" key={q} onClick={() => { setQuery(q); void ask(q); }}>{q}<ArrowRight /></button>)}</section></div> : <div className="context-placeholder"><Network /><strong>No graph context loaded</strong><p>Ask a question to retrieve connected cases, entities and evidence references.</p></div>}</Panel></div>
  </>;
}
