import { useCallback, useState } from 'react';
import { ArrowRight, BookOpenCheck, Filter, Search, ShieldCheck } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { EmptyState, ErrorState, LoadingState, PageHeader, Panel, PriorityIndicator, SourceBadge } from '../components/ui';
import { cases, evidence as evidenceData } from '../data/mockData';
import { useAsync } from '../hooks/useAsync';
import { investigationService } from '../services';
import type { Evidence } from '../types/domain';

export function EvidencePage() {
  const [params, setParams] = useSearchParams(); const caseId = params.get('caseId') ?? ''; const [selected, setSelected] = useState<Evidence>(); const [query, setQuery] = useState('');
  const loader = useCallback(() => investigationService.getEvidence(caseId ? { caseId } : undefined), [caseId]); const { data, loading, error, retry } = useAsync(loader, [loader]);
  const visible = data?.filter((item) => !query || `${item.evidence_id} ${item.relationship} ${item.entityA} ${item.entityB} ${item.provenance.sourceRecordId}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="Evidence-first analysis" title="Evidence Explorer" description="Understand why a relationship is displayed and trace it to the supporting source record." />
    <Panel className="filter-panel"><div className="evidence-search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search evidence ID, entity or source record"/><Filter size={15} /><select value={caseId} onChange={(e) => setParams(e.target.value ? { caseId: e.target.value } : {})}><option value="">All cases</option>{cases.map((c) => <option key={c.case_id}>{c.case_id}</option>)}</select></div></Panel>
    {loading ? <LoadingState /> : error ? <ErrorState message={error} retry={() => void retry()} /> : !visible?.length ? <EmptyState title="No evidence found" /> : <div className="evidence-layout"><Panel title={`${visible.length} supporting records`} subtitle="Select a record to inspect provenance"><div className="evidence-record-list">{visible.map((item) => <button className={selected?.evidence_id === item.evidence_id ? 'active' : ''} onClick={() => setSelected(item)} key={item.evidence_id}><BookOpenCheck size={18} /><div><strong>{item.evidence_id}</strong><span>{item.relationship}</span><small>{item.entityA} <ArrowRight size={11} /> {item.entityB}</small></div><PriorityIndicator value={item.priority} /></button>)}</div></Panel><Panel title="Evidence detail">{selected ? <EvidenceDetail item={selected} /> : <EmptyState title="Select a supporting record" message="The complete provenance and relationship details will appear here." />}</Panel></div>}
  </>;
}

function EvidenceDetail({ item }: { item: Evidence }) { return <div className="evidence-detail"><div className="evidence-detail-head"><ShieldCheck /><div><span>Evidence record</span><h2>{item.evidence_id}</h2></div><PriorityIndicator value={item.priority} /></div><section><span>Relationship</span><div className="relationship-display"><strong>{item.entityA}</strong><span>{item.relationship}<ArrowRight size={14} /></span><strong>{item.entityB}</strong></div></section><section><span>Supporting data</span><p>{item.supportingData}</p></section><dl className="metadata"><div><dt>Case</dt><dd>{item.case_id}</dd></div><div><dt>Evidence type</dt><dd>{item.evidenceType}</dd></div><div><dt>Date / time</dt><dd>{new Date(item.timestamp).toLocaleString('en-IN')}</dd></div><div><dt>Source reliability</dt><dd>{item.sourceReliability}</dd></div></dl><section><span>Provenance</span><SourceBadge>{item.provenance.sourceDataset}</SourceBadge><dl className="metadata"><div><dt>Source record ID</dt><dd>{item.provenance.sourceRecordId}</dd></div><div><dt>Record type</dt><dd>{item.provenance.recordType}</dd></div></dl></section><p className="verification-note">This record supports a displayed relationship; it does not establish guilt. Investigator verification is required.</p></div>; }

export function PriorityLinksPage() {
  const [priority, setPriority] = useState('All'); const records = evidenceData.filter((e) => priority === 'All' || e.priority === priority).slice(0, 9);
  return <><PageHeader eyebrow="Explainable prioritization" title="Priority Links" description="Review relationships ordered by evidence strength and cross-case relevance—not guilt or legal conclusions." />
    <div className="priority-overview"><article><strong>{evidenceData.filter((e) => e.priority === 'High').length}</strong><span>High priority links</span><small>Review supporting evidence first</small></article><article><strong>{evidenceData.filter((e) => e.sourceReliability === 'Record verified').length}</strong><span>Verified source records</span><small>Within demonstration scope</small></article><article><strong>3</strong><span>Cross-case leads</span><small>Across four active cases</small></article></div>
    <Panel title="Prioritized relationships" subtitle="Priority labels are mock service outputs for demonstration" actions={<select value={priority} onChange={(e) => setPriority(e.target.value)}><option>All</option><option>High</option><option>Medium</option><option>Low</option></select>}><div className="priority-table"><div className="table-head"><span>Priority</span><span>Relationship</span><span>Entities</span><span>Supporting factors</span><span>Evidence</span></div>{records.map((item) => <article key={item.evidence_id}><PriorityIndicator value={item.priority} /><strong>{item.relationship}</strong><span>{item.entityA} → {item.entityB}</span><span>{item.sourceReliability} · {item.evidenceType}</span><span>{item.evidence_id}</span></article>)}</div></Panel><p className="page-note">Link Priority helps focus review. It is not a guilt probability, criminal probability, or arrest prediction.</p>
  </>;
}
