import { useRef, useState } from 'react';
import { CheckCircle2, FileText, RotateCcw, Search, UploadCloud } from 'lucide-react';
import { Button, EntityBadge, PageHeader, Panel, SourceBadge } from '../components/ui';

type State = 'ready' | 'processing' | 'completed' | 'error';
const extracted = [
  { type: 'person' as const, label: 'Aarav Mehta', id: 'P-0044' }, { type: 'phone' as const, label: 'Phone ending 104', id: 'PH-0104' }, { type: 'vehicle' as const, label: 'DL 04 NX 0201', id: 'VH-0201' }, { type: 'location' as const, label: 'New Delhi', id: 'L-09' }, { type: 'case' as const, label: 'CASE-001', id: 'CASE-001' },
];

export function FirAnalysisPage() {
  const [state, setState] = useState<State>('ready'); const [fileName, setFileName] = useState(''); const timer = useRef<number | undefined>(undefined);
  const analyse = () => { if (!fileName) return; setState('processing'); timer.current = window.setTimeout(() => setState('completed'), 850); };
  const clear = () => { if (timer.current) window.clearTimeout(timer.current); setState('ready'); setFileName(''); };
  return <><PageHeader eyebrow="Document processing workspace" title="FIR Analysis" description="Submit an FIR for backend OCR and entity extraction. The browser does not process or retain document content." actions={<Button variant="quiet" onClick={clear}><RotateCcw size={15} />Clear</Button>} />
    <div className="fir-grid"><Panel title="Document" subtitle="Select an FIR for analysis"><label className={`upload-zone ${fileName ? 'has-file' : ''}`}><input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" onChange={(e) => { setFileName(e.target.files?.[0]?.name ?? ''); setState('ready'); }} /><UploadCloud /><strong>{fileName || 'Upload or select an FIR'}</strong><span>{fileName ? 'Ready to submit to the configured processing service' : 'PDF, PNG, JPEG or text · frontend selection only'}</span></label><div className="document-actions"><Button onClick={analyse} disabled={!fileName || state === 'processing'}>{state === 'processing' ? <span className="spinner" /> : <Search size={15} />}{state === 'processing' ? 'Analysing FIR...' : 'Analyse FIR'}</Button></div><div className={`processing-status status-${state}`}><i /> <div><strong>{state === 'ready' ? 'Ready' : state === 'processing' ? 'Processing' : state === 'completed' ? 'Completed' : 'Error'}</strong><span>{state === 'ready' ? 'Select a document to begin.' : state === 'processing' ? 'Waiting for the mock processing response.' : state === 'completed' ? 'Demo extraction loaded for review.' : 'Unable to analyse this document.'}</span></div></div><p className="service-disclaimer">Mock mode never uploads this file. Real OCR and extraction require a confirmed backend contract.</p></Panel>
      <Panel title="Extracted text" subtitle={state === 'completed' ? 'Demonstration processing result' : 'Processing output will appear here'}>{state === 'completed' ? <div className="document-text"><div><FileText /><span>Page 1 of 1</span><SourceBadge>Synthetic demo output</SourceBadge></div><p>First Information Report reference FIR/ND/1042/26 records a complaint concerning identity and financial document misuse. The supplied material references Aarav Mehta, a contact number ending 104, vehicle DL 04 NX 0201 and activity recorded in New Delhi.</p><p>These extracted references require review and do not constitute legal findings.</p></div> : <div className="document-placeholder"><FileText /><strong>No extracted text yet</strong><span>Choose a document and start analysis.</span></div>}</Panel>
      <Panel title="Extracted entities" subtitle="Review before adding entities to an investigation graph">{state === 'completed' ? <div className="extracted-list">{extracted.map((item) => <article key={item.id}><EntityBadge type={item.type} /><div><strong>{item.label}</strong><span>{item.id}</span></div><button>Add to graph</button></article>)}<div className="resolution-card"><CheckCircle2 /><div><strong>1 possible identity match</strong><span>Human verification required before confirmation.</span></div><button>Review</button></div></div> : <div className="document-placeholder"><Search /><strong>No entities extracted</strong><span>Entity categories will appear after processing.</span></div>}</Panel></div>
  </>;
}
