import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Network, ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/ui';

export function LoginPage() {
  const [show, setShow] = useState(false); const navigate = useNavigate();
  return <main className="login-page"><section className="login-context"><div className="login-brand"><div><Network /></div><span><strong>NEXUSNET</strong>INTELLIGENCE</span></div><div className="login-message"><span>SIH26189 · Investigative intelligence</span><h1>Connect fragmented records into evidence-backed investigation graphs.</h1><p>Explore cross-case relationships, inspect supporting records and keep every analytical lead subject to human verification.</p><div><span><ShieldCheck />Evidence-first analysis</span><span><Network />Multi-case graph intelligence</span><span><LockKeyhole />Investigator-controlled decisions</span></div></div><small>Investigate · Analyse · Connect</small></section><section className="login-form-wrap"><form onSubmit={(e) => { e.preventDefault(); navigate('/dashboard'); }}><span className="eyebrow">Secure access</span><h2>Investigation workspace</h2><p>Use the demonstration workspace to review the frontend.</p><label>Investigator ID<input required placeholder="Enter investigator ID" autoComplete="username" /></label><label>Password<div><input type={show ? 'text' : 'password'} required placeholder="Enter password" autoComplete="current-password"/><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(!show)}>{show ? <EyeOff /> : <Eye />}</button></div></label><div className="demo-notice"><ShieldCheck /><span><strong>Demonstration access</strong>No credentials are stored or validated while the authentication backend is unavailable.</span></div><Button>Enter workspace <ArrowRight /></Button><small>Access is monitored when connected to an identity service.</small></form></section></main>;
}
