import { useState } from 'react';
import { BookOpenCheck, Search, SlidersHorizontal } from 'lucide-react';
import { Button, EmptyState, PageHeader, Panel, SourceBadge } from '../components/ui';
import { evidence } from '../data/mockData';

export function RetrievalPage() {
  const [query, setQuery] = useState(''); const [submitted, setSubmitted] = useState('');
  const results = submitted ? evidence.filter((e) => e.evidenceType === 'CDR' || e.relationship.includes('COMMUNICATED')).slice(0, 4) : [];
  return <><PageHeader eyebrow="Hybrid evidence retrieval" title="Retrieval" description="Search FIR text and supporting records through the backend retrieval service when connected." />
    <Panel className="retrieval-hero"><span className="eyebrow">Investigation evidence search</span><h2>What records do you need to find?</h2><form onSubmit={(e) => { e.preventDefault(); if (query.trim()) setSubmitted(query); }}><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="e.g. Find FIR records mentioning the same phone number"/><Button>Search evidence</Button></form><div className="prompt-suggestions">{['Find records sharing phone PH-0104', 'Show evidence connecting CASE-017 and CASE-024', 'Locate vehicle references across cases'].map((q) => <button key={q} onClick={() => { setQuery(q); setSubmitted(q); }}>{q}</button>)}</div></Panel>
    {submitted ? <div className="retrieval-layout"><Panel title={`${results.length} relevant records`} subtitle={`Results for “${submitted}”`} actions={<Button variant="quiet"><SlidersHorizontal size={14} />Filters</Button>}><div className="retrieval-results">{results.map((item, index) => <article key={item.evidence_id}><header><BookOpenCheck /><strong>{item.evidence_id}</strong><span>Relevance {(94 - index * 7)}%</span></header><p>{item.supportingData}</p><div><SourceBadge>{item.provenance.sourceDataset}</SourceBadge><span>{item.case_id}</span><span>{item.provenance.sourceRecordId}</span></div></article>)}</div><p className="service-disclaimer">Relevance values shown here are demonstration values. Production scores must be returned by the backend retrieval service.</p></Panel><Panel title="Search context"><dl className="metadata"><div><dt>Search scope</dt><dd>All configured records</dd></div><div><dt>Mode</dt><dd>Mock service</dd></div><div><dt>Backend method</dt><dd>Hybrid retrieval (integration pending)</dd></div></dl><h3>Related entities</h3><div className="id-chips"><span>PH-0104</span><span>P-0044</span><span>P-0188</span><span>CASE-001</span></div></Panel></div> : <EmptyState title="Enter an investigative query" message="Search results will include relevant text, entity references, source records and available evidence." />}
  </>;
}
