import { ArrowRight, CalendarDays, ExternalLink, X } from 'lucide-react';
import { graphData, evidence } from '../data/mockData';
import type { GraphEdge, GraphNode } from '../types/domain';
import { Button, EntityBadge, PriorityIndicator, SourceBadge } from './ui';

export function EntityDetailsPanel({ node, onClose }: { node?: GraphNode; onClose: () => void }) {
  if (!node) return null;
  const relationships = graphData.edges.filter((edge) => edge.source === node.id || edge.target === node.id);
  return <aside className="drawer" aria-label="Entity details"><header><div><EntityBadge type={node.type} /><h2>{node.label}</h2><span>{node.id}</span></div><button onClick={onClose} aria-label="Close entity details"><X /></button></header><div className="drawer-body"><section><h3>Record details</h3><dl className="metadata">{Object.entries(node.metadata).map(([key, value]) => <div key={key}><dt>{key.replaceAll('_', ' ')}</dt><dd>{Array.isArray(value) ? value.join(', ') : value}</dd></div>)}</dl></section><section><h3>Connections</h3><p>{relationships.length} relationships are visible in the current graph scope.</p>{relationships.slice(0, 4).map((edge) => <div className="mini-record" key={edge.id}><span>{edge.relationship}</span><strong>{edge.source === node.id ? edge.target : edge.source}</strong></div>)}</section>{node.provenance && <section><h3>Provenance</h3><SourceBadge>{node.provenance.sourceDataset}</SourceBadge><dl className="metadata"><div><dt>Source record</dt><dd>{node.provenance.sourceRecordId}</dd></div><div><dt>Record type</dt><dd>{node.provenance.recordType}</dd></div></dl></section>}</div><footer><Button variant="secondary"><ExternalLink size={15} />Open full record</Button></footer></aside>;
}

export function EvidenceDrawer({ edge, onClose }: { edge?: GraphEdge; onClose: () => void }) {
  if (!edge) return null;
  const record = evidence.find((item) => edge.evidenceIds.includes(item.evidence_id));
  return <aside className="drawer drawer--evidence" aria-label="Supporting evidence"><header><div><span className="eyebrow">Evidence behind relationship</span><h2>{edge.relationship}</h2><span>{edge.source} <ArrowRight size={13} /> {edge.target}</span></div><button onClick={onClose} aria-label="Close evidence"><X /></button></header><div className="drawer-body">{record ? <><PriorityIndicator value={record.priority} /><section><h3>Supporting record</h3><div className="evidence-callout"><strong>{record.evidence_id}</strong><p>{record.supportingData}</p></div><dl className="metadata"><div><dt>Case</dt><dd>{record.case_id}</dd></div><div><dt>Evidence type</dt><dd>{record.evidenceType}</dd></div><div><dt>Source reliability</dt><dd>{record.sourceReliability}</dd></div><div><dt>Date / time</dt><dd>{new Date(record.timestamp).toLocaleString('en-IN')}</dd></div></dl></section><section><h3>Provenance</h3><SourceBadge>{record.provenance.sourceDataset}</SourceBadge><dl className="metadata"><div><dt>Source record</dt><dd>{record.provenance.sourceRecordId}</dd></div><div><dt>Record type</dt><dd>{record.provenance.recordType}</dd></div></dl></section><p className="verification-note">This connection is an investigative lead and requires human verification.</p></> : <p>No supporting record is available in the current data scope.</p>}</div><footer><Button><ExternalLink size={15} />View evidence</Button><Button variant="secondary"><CalendarDays size={15} />Timeline</Button></footer></aside>;
}
